trigger:
  branches:
    include:
      - release/staging
  paths:
    include:
      - src/manage/**

pool:
  vmImage: ubuntu-latest

  variables:
    - group: dev

steps:
  # Step 1: Set up Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
      checkLatest: true

  # Step 2: Install dependencies
  - script: |
      cd src/manage
      npm ci
    displayName: "Install dependencies"

  # Build the app using Vite (via npm script)
  - script: |
      cd src/manage
      npm run build  
    displayName: "Build Vite Project"
    continueOnError: false

  # Step 4: Deploy to Azure Static Web App
  - task: AzureStaticWebApp@0
    continueOnError: false
    inputs:
      azure_static_web_apps_api_token: $(azure_static_web_apps_api_token_manage)
      app_location: "src/manage"
      api_location: ""
      output_location: "dist"
      app_build_command: "npm run build"
      api_build_command: "rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache"
